module.exports = {
  container: {
    width: '100%',
    height: '100%',
    borderRadius: 12,
  },
  header: {
    height: '10%',
    width: '100%',
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#4edf86',
    borderBottomWidth: 0.5,
    borderColor: 'rgba(0, 0, 0, 0.3)',
  },
  title: {
    width: '100%',
    height: '100%',
    fontSize: 48,
    lineHeight: 120,
    textAlign: 'center',
    fontWeight: 'bold',
    borderBottomWidth: 6,
    borderColor: '#000000',
    verticalAlign: 'middle',
  },
  tabs: {
    width: '100%',
    height: '5%',
    flexDirection: 'row',
  },
  tab1: {
    width: '33.3%',
    height: '100%',
    textAlign: 'center',
    fontSize: 36,
    lineHeight: 60,
    backgroundColor: '#ffffff',
  },
  tab2: {
    width: '33.3%',
    height: '100%',
    textAlign: 'center',
    fontSize: 36,
    lineHeight: 60,
    backgroundColor: '#ffffff',
  },
  tab3: {
    width: '33.3%',
    height: '100%',
    textAlign: 'center',
    fontSize: 36,
    lineHeight: 60,
    backgroundColor: '#ffffff',
  },
  rankList: {
    width: '100%',
    height: '100%',
    // marginTop: 10,
  },
  list: {
    width: '100%',
    height: '100%',
    backgroundColor: '#ffffff',
  },
  listItem: {
    width: '100%',
    height: 100,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ff8000',
  },
  listItemOld: {
    width: '100%',
    height: 100,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#515e65',
  },
  listItemNum: {
    width: '15%',
    height: 50,
    fontSize: 32,
    fontWeight: 'bold',
    lineHeight: 45,
    textAlign: 'center',
    // verticalAlign: 'middle',
  },
  listHeadImg: {
    width: 100,
    height: 100,
    borderRadius: 15,
    borderWidth: 5,
    borderColor: 'red',
  },
  listItemName: {
    width: '20%',
    height: 150,
    textAlign: 'center',
    fontSize: 36,
    lineHeight: 150,
    marginLeft: 50,
    // backgroundColor: '#e23c2f',
  },
  listItemScore: {
    width: '20%',
    height: 150,
    fontSize: 30,
    fontWeight: 'bold',
    lineHeight: 150,
    lineWidth: 150,
    textAlign: 'right',
    // backgroundColor: '#23d96e',
  },
  listScoreUnit: {
    width: '10%',
    height: 150,
    opacity: 1,
    color: '#3370ff',
    textAlign: 'left',
    fontWeight: 'bold',
    fontSize: 35,
    lineHeight: 150,
    // backgroundColor: '#009eff',
  },
  selfListItem: {
    width: '100%',
    height: '15%',
    borderRadius: 20,
    backgroundColor: '#D2691E',
    alignItems: 'center',
  },
  listTips: {
    width: '100%',
    height: '10%',
    lineHeight: 90,
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 30,
    color: 'rgba(0,0,0,0.5)',
    backgroundColor: '#ffffff',
    borderRadius: 10,
    alignItems: 'center',
  }
}